### ISSUE TITLE
Autofill System Issues in Code Editor

### ISSUE THREAD

**Issue by HawToo** [RaleaAlexei/Synapse-ZUI#1]
The autofill system in the code editor is causing significant issues when writing code. For example, if you type:

`for i, v in pairs() do`

The system frequently replaces do and other keywords with irrelevant suggestions, which is both disruptive and counterproductive. Additionally, the only way to avoid triggering autofill is by actively interacting with the suggestions—either by clicking with your mouse or using the arrow keys. This makes the workflow unnecessarily cumbersome and frustrating, especially when you simply want to proceed without selecting an autofill option.

Could you please improve the autofill system to better align with common coding patterns, avoid inappropriate replacements for keywords, and allow users to bypass autofill easily without needing additional interactions? These changes would greatly enhance the overall coding experience.

https://github.com/user-attachments/assets/c17018f7-92f3-4594-9958-d66d60df3e83

**Comment by RaleaAlexei** [comment]
Fixed for the do statement
